repos:
- repo: local
  hooks:
  - id: mako_dependencies_check
    name: Schema template file dependencies up to date
    always_run: true
    language: system
    entry: sh
    args:
      - "-c"
      - |
        if ! make -C code/schemas -q dependencies.mk; then
          echo "ERROR: Mako schema template dependencies are out of date. Run:"
          echo "    make -C code/schemas -q dependencies.mk"
          echo "and commit the changes, then try again."
          exit 1
        fi
