target-version = "py312"

[lint]
exclude = ["docs/*"]
select = ["ALL"]
extend-ignore = [
    "ANN401",  # Forbids `Any` as a type annotation
    "COM812",  # Ruff docs say this conflicts with the autoformatter
    "CPY001",  # Requires copyright notice in every file
    "D105",    # Forces documentation on magic methods
    "D107",    # Conflicts with Google docstring style re: __init__()
    "DTZ",     # Forces all datetimes to use time zones
    "EM",      # Opinions about error messages that I vehemently disagree with
    "ERA001",  # Overzealous detection of commented-out code
    "FBT",     # Takes umbrage at any boolean positional argument
    "FIX002",  # Disallows FIXME comments
    "PLR2004", # Overzealous detection of "magic constants"
    "TD003",   # Requires links on all TODOs
    "TRY003",  # Gripes about exceptions with "long" error messages. I like details.
]

[lint.per-file-ignores]
"__init__.py" = ["F403", "PLC0414"]
"src/schemas/scripts/schemas.py" = ["I002", "N815", "TC003"]
"Makefile.py" = ["I002", "TC003"]

[lint.isort]
force-single-line = true
lines-after-imports = 2
order-by-type = false
required-imports = ["from __future__ import annotations"]

[lint.mccabe]
max-complexity = 9

[lint.flake8-annotations]
mypy-init-return = true

[lint.pydocstyle]
convention = "google"
