flowchart TD
    start                       -- is record?  --> parse_record
    start                       -- is eof?     --> eof
    parse_record[parse record]  -- is record?  --> parse_record
    parse_record                -- is eof?     --> eof
