flowchart TB
    header[parse header]
    disenrollment[parse disenrollment]
    enrollment[parse enrollment]
    4rx_data_change[parse 4rx_data_change]

    start --> header
    header --> decide_record
    header -- is disenrollment? --> disenrollment
    header -- is enrollment? --> enrollment
    disenrollment -- is trailer? --> trailer
    disenrollment --> decide_record
    enrollment -- is trailer? --> trailer
    enrollment --> decide_record
    4rx_data_change -- is trailer? --> trailer
    4rx_data_change --> decide_record
    trailer --> end
