#!/usr/bin/env python3

from __future__ import annotations

import pathlib
import sys
import typing

import click
import mako.lookup
import mako.template
from mako.exceptions import MakoException


if typing.TYPE_CHECKING:
    from collections.abc import Mapping
    from collections.abc import Sequence
    from typing import Any
    from typing import TextIO

THIS_FILE = pathlib.Path(__file__)
HERE = THIS_FILE.parent
SCHEMAS_ROOT_DIR = HERE.parent


@click.argument(
    "sources", type=click.Path(exists=True, dir_okay=False, allow_dash=True), nargs=-1
)
@click.option(
    "-o",
    "--output",
    type=click.File(mode="w", atomic=True),
    help="The file to write the output to. Use `-` or omit to write to stdout.",
)
@click.option(
    "-M",
    "track_dependencies",
    is_flag=True,
    help="Instead of rendering the templates, track which files are imported and"
    " generate Makefile rules for establishing dependencies between these files.",
)
@click.option(
    "-I",
    "include",
    type=click.Path(exists=True, file_okay=False, path_type=pathlib.Path),
    multiple=True,
    help="Add the given directory to the template search path. Specify multiple times"
    " to add multiple directories. They will be searched in the order the paths are"
    " provided.",
)
@click.option(
    "-D",
    "define",
    multiple=True,
    help='Define a constant X set to the string Y with the syntax "X=Y". The forms "X="'
    ' and "X" will define X as an empty string.',
)
@click.command()
def main(
    define: Sequence[str],
    include: Sequence[pathlib.Path],
    output: TextIO,
    sources: Sequence[str],
    track_dependencies: bool,
) -> None:
    """Render mako template files.

    The output is the concatenation of all inputs.
    """
    search_directories = [p.absolute() for p in include[::-1]] + [pathlib.Path.cwd()]
    lookup = DependencyTrackingLookup(directories=search_directories)

    if track_dependencies:
        output.write("# Autogenerated file. DO NOT EDIT.\n")

    definitions = dict(item.partition("=")[::2] for item in define)
    for file in sources:
        try:
            text, dependencies = render_single_file(file, lookup, definitions)
        except MakoException as err:
            click.echo(str(err), err=True)
            sys.exit(1)

        if not track_dependencies:
            output.write(text)
        elif dependencies:
            output.write(f"{file}: " + " ".join(sorted(dependencies)) + "\n")


def render_single_file(
    file: str, lookup: DependencyTrackingLookup, definitions: Mapping[str, str]
) -> tuple[str, set[str]]:
    """Render a single Mako template file."""
    lookup.imported_uris.clear()
    if file == "-":
        template = mako.template.Template(
            sys.stdin.read(), filename="stdin", lookup=lookup
        )
    else:
        template = mako.template.Template(filename=file, lookup=lookup)

    result = typing.cast("str", template.render(**definitions))
    return result, lookup.imported_uris


class DependencyTrackingLookup(mako.lookup.TemplateLookup):
    """A template lookup class that tracks which files are imported."""

    imported_uris: set[str]

    def __init__(self, *args: Any, **kwargs: Any):
        super().__init__(*args, **kwargs)
        self.imported_uris = set()

    def get_template(self, uri: str) -> mako.template.Template:
        template = super().get_template(uri)
        abs_template_path = pathlib.Path(template.filename)
        relative_template_path = abs_template_path.relative_to(SCHEMAS_ROOT_DIR)
        self.imported_uris.add(str(relative_template_path))
        return template


if __name__ == "__main__":
    main()
