# SPDX-License-Identifier: BSD-3-Clause

"""Per-format doit task generation — the core orchestrator."""

from __future__ import annotations

import configparser
import logging
import os
import re
from pathlib import Path
from typing import Any
from typing import TYPE_CHECKING

from .build_rules import enumerate_file_dependencies
from .build_rules import enumerate_identical_files
from .build_rules import enumerate_identical_versions
from .constants import BUILD_DIR
from .file_ops import link_or_copy
from .render_tasks import render_template_task
from .render_tasks import yaml_postprocess_tasks


LOG = logging.getLogger(__name__)

if TYPE_CHECKING:
    from collections.abc import Collection
    from collections.abc import Mapping
    from collections.abc import MutableMapping

    from .versions import VersionSpec


TaskDict = dict[str, Any]


def _path_to_slug(p: Path) -> str:
    return str(p.relative_to(BUILD_DIR)).replace(os.sep, "_").replace(".", "_")


def tasks_for_source_file(
    source_file: Path,
    version_build_dir: Path,
    extra_file_deps: Collection[Path] = (),
) -> list[TaskDict]:
    """Generate doit task dicts for a single source file in a records directory."""
    tasks: list[TaskDict] = []

    if source_file.suffix == ".liquid":
        rendered_name = source_file.stem
        is_yaml = Path(rendered_name).suffix == ".yaml"

        if is_yaml:
            rendered_path = version_build_dir / (
                Path(rendered_name).stem + ".rendered.yaml"
            )
        else:
            rendered_path = version_build_dir / rendered_name

        tasks.append(render_template_task(source_file, rendered_path, extra_file_deps))

        if is_yaml:
            tasks.extend(
                yaml_postprocess_tasks(
                    rendered_path,
                    version_build_dir,
                    output_stem=Path(rendered_name).stem,
                )
            )
            # Clean up intermediate rendered YAML when `doit clean` is run.
            tasks[-1].setdefault("clean", []).append(
                (Path.unlink, [rendered_path], {"missing_ok": True})
            )
        # Non-YAML liquid files are already handled by the render task.

    elif source_file.suffix == ".yaml":
        tasks.extend(
            yaml_postprocess_tasks(source_file, version_build_dir, extra_file_deps)
        )

    return tasks


def tasks_for_file_builds(
    source_path: Path,
    target_root: Path,
    dep_map: Mapping[Path, Collection[Path]],
) -> list[TaskDict]:
    """Generate render/postprocess/convert tasks for all source files in a format."""
    tasks: list[TaskDict] = []

    for version_dir in sorted(source_path.iterdir()):
        if not re.match(r"\d+\.\d+$", version_dir.name) or not version_dir.is_dir():
            continue

        records_dir = version_dir / "records"
        if not records_dir.exists():
            continue

        version_build_dir = target_root / version_dir.name / "records"

        for source_file in sorted(records_dir.iterdir()):
            if not source_file.is_file():
                continue

            extra_deps = dep_map.get(source_file.resolve(), [])
            tasks.extend(
                tasks_for_source_file(
                    source_file,
                    version_build_dir,
                    extra_file_deps=extra_deps,
                )
            )

    return tasks


def tasks_for_identical_versions(
    parent_version: VersionSpec,
    child_versions: Collection[VersionSpec],
    format_name: str,
    format_build_root: Path,
    already_handled: MutableMapping[VersionSpec, str],
) -> list[TaskDict]:
    """Create tasks that symlink/copy child version directories from a parent."""
    child_set = set(child_versions)
    collisions = child_set & already_handled.keys()

    if collisions:
        raise ValueError(
            f"In {format_name!r} build rules, some versions are generated by multiple"
            " parents. This likely means the constraints are too lax.\n"
            f"Parent: {parent_version}\n"
            f"Children: {', '.join(map(str, child_versions))}\n"
            "Collisions:\n - "
            + "\n - ".join(
                f"{v} already generated by {already_handled[v]}" for v in collisions
            )
        )

    parent_output_dir = format_build_root / str(parent_version)
    child_output_dirs = [format_build_root / str(v) for v in child_versions]

    child_version_strings = ", ".join(map(str, child_versions))
    tasks = [
        {
            "name": f"_cp_{format_name}_{parent_version.major}_{parent_version.minor}",
            "doc": f"Clone {format_name} v{parent_version} to: {child_version_strings}",
            "actions": [(link_or_copy, [parent_output_dir, child_output_dirs])],
            "task_dep": [f"build:{_path_to_slug(parent_output_dir)}"],
            "uptodate": [all(d.exists() for d in child_output_dirs)],
            "targets": [str(d) for d in child_output_dirs],
        }
    ]

    already_handled.update(dict.fromkeys(child_versions, str(parent_version)))
    return tasks


def generate_tasks_for_format(source_path: Path) -> list[TaskDict]:
    """Generate all doit task dicts for a given file format."""
    format_name = source_path.stem
    build_rules_file = source_path / "build_rules.ini"

    if not build_rules_file.exists():
        LOG.warning(
            "Format %r doesn't have the required build rules file. Ignoring for now,"
            " but this may become an error in the future.",
            format_name,
        )
        return []

    build_rules = configparser.ConfigParser()
    build_rules.read(build_rules_file)

    target_root = BUILD_DIR / format_name
    already_handled: dict[VersionSpec, str] = {}
    all_tasks: list[TaskDict] = []

    # --- Identical versions (symlink/copy entire version dirs) ---
    identical_versions = enumerate_identical_versions(build_rules)

    for parent_version, children in identical_versions.items():
        already_handled[parent_version] = "(Defined)"
        all_tasks.extend(
            tasks_for_identical_versions(
                parent_version=parent_version,
                child_versions=children,
                format_name=format_name,
                format_build_root=target_root,
                already_handled=already_handled,
            )
        )

    # --- File dependencies: map parent templates to their dependents ---
    dep_map = enumerate_file_dependencies(build_rules, source_path)

    # --- Identical files: add extra file_dep entries ---
    identical_files = enumerate_identical_files(build_rules, source_path)
    for upstream_file, downstream_files in identical_files.items():
        for downstream in downstream_files:
            dep_map.setdefault(downstream, []).append(upstream_file)

    # --- Per-file render/postprocess tasks ---
    file_tasks = tasks_for_file_builds(source_path, target_root, dep_map)
    all_tasks.extend(file_tasks)

    return all_tasks
