# SPDX-License-Identifier: BSD-3-Clause

"""Per-format doit task generation — the core orchestrator."""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any
from typing import TYPE_CHECKING

from .build_rules import parse_build_rules
from .file_ops import link_or_copy
from .render_tasks import _path_to_slug
from .render_tasks import render_template_task
from .render_tasks import yaml_postprocess_tasks


LOG = logging.getLogger(__name__)

if TYPE_CHECKING:
    from collections.abc import Collection
    from collections.abc import Mapping
    from collections.abc import MutableMapping

    from .versions import VersionSpec


TaskDict = dict[str, Any]


def tasks_for_source_file(
    source_file: Path,
    version_build_dir: Path,
    extra_file_deps: Collection[Path] = (),
    *,
    output_root: Path,
) -> list[TaskDict]:
    """Generate doit task dicts for a single source file in a records directory."""
    tasks: list[TaskDict] = []

    if source_file.suffix == ".liquid":
        rendered_name = source_file.stem
        is_yaml = Path(rendered_name).suffix == ".yaml"

        if is_yaml:
            rendered_path = version_build_dir / (
                Path(rendered_name).stem + ".rendered.yaml"
            )
        else:
            rendered_path = version_build_dir / rendered_name

        tasks.append(
            render_template_task(
                source_file, rendered_path, extra_file_deps, output_root=output_root
            )
        )

        if is_yaml:
            tasks.extend(
                yaml_postprocess_tasks(
                    rendered_path,
                    version_build_dir,
                    output_stem=Path(rendered_name).stem,
                    output_root=output_root,
                )
            )
            # Clean up intermediate rendered YAML when `doit clean` is run.
            tasks[-1].setdefault("clean", []).append(
                (Path.unlink, [rendered_path], {"missing_ok": True})
            )
        # Non-YAML liquid files are already handled by the render task.

    elif source_file.suffix == ".yaml":
        tasks.extend(
            yaml_postprocess_tasks(
                source_file, version_build_dir, extra_file_deps, output_root=output_root
            )
        )

    return tasks


def tasks_for_file_builds(
    source_path: Path,
    target_root: Path,
    dep_map: Mapping[Path, Collection[Path]],
    *,
    output_root: Path,
) -> list[TaskDict]:
    """Generate render/postprocess/convert tasks for all source files in a format."""
    tasks: list[TaskDict] = []

    for version_dir in sorted(source_path.iterdir()):
        if not re.match(r"\d+\.\d+$", version_dir.name) or not version_dir.is_dir():
            continue

        records_dir = version_dir / "records"
        if not records_dir.exists():
            continue

        version_build_dir = target_root / version_dir.name / "records"
        version_tasks: list[TaskDict] = []

        for source_file in sorted(records_dir.iterdir()):
            if not source_file.is_file():
                continue

            extra_deps = dep_map.get(source_file.resolve(), [])
            version_tasks.extend(
                tasks_for_source_file(
                    source_file,
                    version_build_dir,
                    extra_file_deps=extra_deps,
                    output_root=output_root,
                )
            )

        if version_tasks:
            tasks.extend(version_tasks)
            tasks.append(
                {
                    "name": _path_to_slug(target_root / version_dir.name, output_root),
                    "actions": None,
                    "task_dep": [f"build:{t['name']}" for t in version_tasks],
                }
            )

    return tasks


def tasks_for_identical_versions(  # noqa: PLR0913
    parent_version: VersionSpec,
    child_versions: Collection[VersionSpec],
    format_name: str,
    format_build_root: Path,
    already_handled: MutableMapping[VersionSpec, str],
    *,
    output_root: Path,
) -> list[TaskDict]:
    """Create tasks that symlink/copy child version directories from a parent."""
    child_set = set(child_versions)
    collisions = child_set & already_handled.keys()

    if collisions:
        raise ValueError(
            f"In {format_name!r} build rules, some versions are generated by multiple"
            " parents. This likely means the constraints are too lax.\n"
            f"Parent: {parent_version}\n"
            f"Children: {', '.join(map(str, child_versions))}\n"
            "Collisions:\n - "
            + "\n - ".join(
                f"{v} already generated by {already_handled[v]}" for v in collisions
            )
        )

    parent_output_dir = format_build_root / str(parent_version)
    child_output_dirs = [format_build_root / str(v) for v in child_versions]

    child_version_strings = ", ".join(map(str, child_versions))
    tasks = [
        {
            "name": f"_cp_{format_name}_{parent_version.major}_{parent_version.minor}",
            "doc": f"Clone {format_name} v{parent_version} to: {child_version_strings}",
            "actions": [(link_or_copy, [parent_output_dir, child_output_dirs])],
            "task_dep": [f"build:{_path_to_slug(parent_output_dir, output_root)}"],
            "uptodate": [all(d.exists() for d in child_output_dirs)],
            "targets": [str(d) for d in child_output_dirs],
        }
    ]

    already_handled.update(dict.fromkeys(child_versions, str(parent_version)))
    return tasks


def generate_tasks_for_format(source_path: Path, *, build_dir: Path) -> list[TaskDict]:
    """Generate all doit task dicts for a given file format."""
    format_name = source_path.stem
    build_rules_file = source_path / "build_rules.yaml"

    if not build_rules_file.exists():
        LOG.warning(
            "Format %r doesn't have the required build rules file. Ignoring for now,"
            " but this may become an error in the future.",
            format_name,
        )
        return []

    rules = parse_build_rules(build_rules_file, source_path)

    target_root = build_dir / format_name
    already_handled: dict[VersionSpec, str] = {}
    all_tasks: list[TaskDict] = []

    # File tasks first — these also create per-version grouping tasks that the
    # identical-version copy tasks depend on.
    all_tasks.extend(
        tasks_for_file_builds(
            source_path, target_root, rules.file_dep_map, output_root=build_dir
        )
    )

    built_version_slugs = {t["name"] for t in all_tasks}

    for parent_version, children in rules.identical_versions.items():
        parent_slug = _path_to_slug(target_root / str(parent_version), build_dir)
        if parent_slug not in built_version_slugs:
            LOG.debug(
                "Skipping identical-version rule for %s v%s: no file tasks found.",
                format_name,
                parent_version,
            )
            continue

        already_handled[parent_version] = "(Defined)"
        all_tasks.extend(
            tasks_for_identical_versions(
                parent_version=parent_version,
                child_versions=children,
                format_name=format_name,
                format_build_root=target_root,
                already_handled=already_handled,
                output_root=build_dir,
            )
        )

    return all_tasks
