@startuml

_START --> AssertIsHeader : ASSERT header
AssertIsHeader --> ParseHeader : PARSE header

ParseHeader --> CheckIfDetail : CHECK detail
ParseHeader --> CheckIfTrailer : CHECK trailer

CheckIfDetail --> ParseDetail : PARSE detail

ParseDetail --> CheckIfDetail
ParseDetail --> CheckIfTrailer

CheckIfTrailer --> ParseTrailer : PARSE trailer
ParseTrailer --> AssertEOF

@enduml
